spring:
  profiles:
    active: qa
  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: none
---
logging:
  level:
    me.d3249.demo.krugervacunas: DEBUG

spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:h2:mem:vacunacion
  sql:
    init:
      data-locations: classpath:sql/data/datos_iniciales.sql
      schema-locations: classpath:sql/schema/h2_schema.sql
kruger:
  vacunas:
    usuario: admin
    password: password
    capacidad_diaria: 5
---
spring:
  config:
    activate:
      on-profile: qa
  datasource:
    url: ${PG_URL}
    username: ${PG_USERNAME}
    password: ${PG_PASSWORD}
  sql:
    init:
      data-locations: classpath:sql/data/datos_iniciales.sql
      schema-locations: classpath:sql/schema/pg_schema.sql
kruger:
  vacunas:
    usuario: ${ADMIN}
    password: ${PASSWORD}
    capacidad_diaria: 5
